!include data.multi30k.de-en.yaml
!include transformer.small.yaml
!include translator.greedy.yaml
!include train.small.yaml

# no learning rate scheduler

loss:
  name: TranslationLoss
  # no label smoothing
